version: "3.8"
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=html_mail_editor_development
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: html_mail_editor_development
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    command: yarn serve
